[package]
name = "redisx"
version = "0.2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
redis-module = { git="https://github.com/RedisLabsModules/redismodule-rs.git", branch="hash_get_set", features = ["experimental-api"]}